Storybook Refactoring
adobe/spectrum-web-components pull request #1287
Opened 2021-03-11 23:11 UTC by najikahalsema

Refactoring our storybook to have a more user-friendly and straightforward experience. This is the first effort. More controls will be added to the storybook in the future. 

## Description

Added controls to the following components: accordion, action button, action group, action menu, banner, button, card, dialog, dropzone, picker, popover, radio, split button, toast, tooltip 

## Related Issue

fixes https://github.com/adobe/spectrum-web-components/issues/1223 

## Motivation and Context

Better user experience, less storybook crashing

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-03-12 00:59 UTC, Westbrook reviewed
First couple of nits. The next round of review gets into the actual stories, and I'd like to have the preview site building in CI to compare the output against, but the tests are currently failing. Once that's going green again, I'll dive in some more!

2021-03-12 00:59 UTC, Westbrook commented on .storybook/main.js
> +        // '../packages/*/stories/*.stories.js'
Once you feel like ALL of the stories are structured inline with how you'd like them to be in terms of the usage of Storybook@6, feel free to use this listing and delete the individually listed backed below. There's already a handful of patterns not listed therein, e.g. color elements, thumbnail, etc.

2021-03-12 00:59 UTC, Westbrook commented on .storybook/main.js
> +    // },
This was also some notes that can be removed for now.

2021-03-12 00:59 UTC, Westbrook commented on .storybook/preview.js
> +// import customElemenents from '../custom-elements.json';
If we're comfortable with the args listing at current can remove this comment and the one at the end of the file? We can also remove the unused import of `setCustomElements`, right?

2021-03-12 00:59 UTC, Westbrook commented on .storybook/types.d.ts
> +import { TemplateResult } from '@spectrum-web-components/base';
I think we ended up not using this type?

2021-03-12 00:59 UTC, Westbrook commented on package.json
> +        "@web/test-runner-commands": "^0.4.1",
This bad merged the junit reporter out of the project...IIUC.

2021-03-15 12:44 UTC, Westbrook requested changes
It also looks like you're not caught up to master, which is what prevents you from being able to update the golden images cache.

Good that it did, because I think most of those changes are errors of some kind...happy to go through those with you, or we can prioritize the review UI to make understanding the diffs easier.

2021-03-15 18:39 UTC, najikahalsema commented on packages/accordion/stories/accordion.stories.ts
> +        },
I was planning to add those as we expose more of the controls, but I can add descriptions to the ones that have controls in this pass if they don't have them already.

2021-03-15 19:52 UTC, najikahalsema commented on packages/button/stories/button-overBackground.stories.ts
> +        <p style="color: white">
I only need it in this one place because the text wouldn't display properly on the background? But I can use a custom variable.

2021-03-15 22:27 UTC, najikahalsema commented on packages/tabs/stories/tabs.stories.ts
> +    },
I didn't touch this component, so I'll make sure to refactor this in a later pass!

2021-03-16 22:59 UTC, Westbrook reviewed
I'm gonna take another look at this in the morning, but it's looking much closer. The main thing that I see right now is that you've used `feat:` and `fix:` a bunch in your commits. These commits will trigger version changes (`0.x.0` for "feat" and `0.0.x` for "fix) that I don't see as being required by these changes. To the best that I can see, only `packages/radio/src/Radio.ts` has actual user facing changes in it. There are a couple of comments added to Base and Shared, but no actual functional code. I think we want to edit most of those commits to be `docs:` or in some cases `test:`. Alternatively, you could squash the commits to be even simpler, something like `docs: update to @web/dev-server-storybook`, `fix(radio): add invalid property`, and `ci: update golden image cache` or so...

2021-03-16 22:59 UTC, Westbrook commented on projects/story-decorator/src/StoryDecorator.ts
> +ActiveOverlay.prototype.renderTheme = function (
This looks like a bad merge. See line 81 above.

2021-03-16 22:59 UTC, Westbrook commented on packages/popover/stories/popover.stories.ts
> +import { Placement } from '@spectrum-web-components/overlay/src/popper';
Is `Placement` available in the main entry point `'spectrum-web-components/overlay'`?

2021-03-17 22:26 UTC, Westbrook commented on packages/split-button/test/split-button.test.ts
> +    it('loads [type="field"] splitbutton accessibly with deprecated syntax', async () => {
Looks like this test got duplicated in a merge somewhere? See like 72 below.

2021-03-17 22:32 UTC, Westbrook reviewed
LGTM! Thanks for getting this first pass together, looking forward to where we can go with this.

Assuming CI passes, merge away!

2021-03-17 22:47 UTC, merged