chore: focus pre-commit cmds on staged assets
adobe/spectrum-web-components pull request #2383
Opened 2022-06-27 18:34 UTC by castastrophe

## Description

Capture more information on staged files & run linting commands on them in a more targeted way. Ensure commands are run only if files are present in stage.

## Motivation and context

- Prevent stray *.css linting errors from being included if the PR in-question didn't touch the file.
- Auto-fix where possible and commit that update

## How has this been tested?

-   [x] _Remove a copyright header from a *.js and *.css file_
    1. Commit to the branch 
    2. Check that auto-fix corrects the *.js and the *.css file in question

<img width="986" alt="Screen Shot 2022-06-27 at 2 35 49 PM" src="https://user-images.githubusercontent.com/1840295/176011979-91d5ca9b-a7df-43f0-8a47-62c3f21814e1.png">

## Types of changes

-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2022-06-27 18:51 UTC, Westbrook requested changes
Interesting that I don't feel like I've ever run into this, but cool to scope those commands a little more!

Clean up that one dupe and we're good to go!

2022-06-27 18:51 UTC, Westbrook commented on .husky/pre-commit
> +# yarn analyze:quick
Please remove.

2022-06-29 15:01 UTC, castastrophe commented on .husky/pre-commit
> +# yarn analyze:quick
```suggestion
```

2022-06-29 15:02 UTC, castastrophe commented on .husky/pre-commit
> +# yarn analyze:quick
Great catch!  Pushed up that fix.

2022-06-29 15:18 UTC, merged