refactor(action-group): use core tokens
adobe/spectrum-web-components pull request #2530
Opened 2022-08-23 14:18 UTC by pfulton

Adds a beta version of the new ActionGroup component.

Uses beta release, hold for full release.

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2022-08-30 16:43 UTC, pfulton commented
Looks like there are a few things related to `margin` that I need to check on with this one.

2022-09-21 17:11 UTC, pfulton commented
@Westbrook I think the missing thing here is the application of the t-shirt sizes. I tried taking a shot at applying them, but I think I'm missing something. The component doesn't actually seem to be applying the styles for a given size. Any thoughts?

2022-09-21 18:35 UTC, Westbrook commented
First, looks like you've haven't run `yarn` since you set up the t-shirt size support.

Second, is there a preview of what t-shirt sizing should open up here?

Third, could you add something like what @bernhard-adobe did [here](https://github.com/adobe/spectrum-web-components/pull/2561/files#diff-a628c92d8f0ec744af84fee5287b28c15fa3f268b48b5870117915bad1dd808c) to document the t-shirt sizes in Storybook?

2022-09-22 18:08 UTC, pfulton commented
@Westbrook let me know if these new stories will suffice for now. Also, if I did anything silly, let me know!

2022-09-22 19:41 UTC, pfulton commented
Also, I just graduated this component from `beta` over in the CSS repo. If you'd like me to switch to that release, let me know and I can make that adjustment!

2022-09-22 21:12 UTC, Westbrook requested changes
Couple of notes and then we should be good to bump the version on this and the VRT hash and merge!

2022-09-22 21:12 UTC, Westbrook commented on packages/action-group/README.md
> +## Sizes
Can we do this like these: https://github.com/adobe/spectrum-web-components/pull/2561/files#diff-cf4b0c014149d7962740bdc8188c60f4e4f91b5c9f4c1ad195bd94b2ad9d7a26R61-R97 in place of these: https://github.com/adobe/spectrum-web-components/blob/main/packages/action-group/README.md?plain=1#L27-L44

2022-09-22 21:12 UTC, Westbrook commented on packages/action-group/stories/action-group-tooltip.stories.ts
> +                <sp-action-button slot="trigger" size=${args.size}>
I think you mean for this to be on the `<sp-action-group>` on like 148 instead of on these individually, right?

2022-09-22 21:12 UTC, Westbrook commented on packages/action-group/stories/action-group-sizes.stories.ts
> +            <sp-action-button size=${args.size}>Button 1</sp-action-button>
I think you're passing the `size` internally, so they don't need to be on each Action Button anymore, right?

2022-09-22 21:12 UTC, Westbrook commented on packages/action-group/stories/action-group.stories.ts
> +            <sp-action-button label="Properties" size=${args.size}>
Same?

2022-09-22 21:12 UTC, Westbrook commented on packages/action-group/test/action-group.test.ts
> +    it('');
I love tests, but maybe not this one? 😉

2022-09-23 13:08 UTC, pfulton commented on packages/action-group/test/action-group.test.ts
> +    it('');
Oh dang.

2022-09-23 15:32 UTC, Westbrook commented on packages/action-group/src/ActionGroup.ts
> +            (changes.has('size') && this.size)
Has a cascade effect on the Action Button stories that had previously leveraged Action Group without a size, and not the default to `m` causes visual effects. This is a nice feature add, but it'll be important to include this information in our release announcement.

2022-10-11 21:31 UTC, Westbrook approved these changes
Ship it!

2022-10-11 21:31 UTC, merged