[DRAFT] chore(menu): convert to lightningcss
adobe/spectrum-web-components pull request #3116
Opened 2023-04-13 17:00 UTC by najikahalsema

A draft to test if it passes VRTs
## Description

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2023-04-14 16:21 UTC, najikahalsema commented on packages/menu/src/spectrum-config.js
> +                    replace: [
It works now! That's before we figured out how to spell 😉

2023-04-14 17:20 UTC, najikahalsema commented
> CI says you didn't run `yarn`/`yarn process-spectrum` before you last commit.

I'm working on it!!! There's still some things left to convert with that whole `host:not(disabled)` whatever

2023-04-16 22:31 UTC, Westbrook requested changes
LGTM. Please pull out the `spectrum-config.v1.js` file and then we'll merge this in!

2023-04-18 22:57 UTC, Westbrook approved these changes
Love to see it!

Here we mark the passing of a good friend who got us through many a difficult Spectrum CSS upgrades, but left of confused and with more work than we wanted it their old age. Long live the king!

2023-04-18 22:58 UTC, merged