fix(color-wheel): should reorient with dir="rtl" #3317
adobe/spectrum-web-components pull request #3319
Opened 2023-06-14 19:20 UTC by majornista

## Description

## Related issue(s)

- #3317 

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2023-06-30 16:49 UTC, hunterloftis requested changes
@majornista thanks for putting this PR together. Could you add a test to verify that these RTL interactions work as expected?

2023-07-11 19:39 UTC, majornista commented
@hunterloftis I think we already cover the interactions with https://github.com/adobe/spectrum-web-components/blob/ca2acdafe004cb962c00ebb7f79c5b6061dc6843/packages/color-wheel/test/color-wheel.test.ts#L261C2-L309C8

2023-07-12 14:28 UTC, hunterloftis submitted a review, later dismissed
Thanks @majornista!

2023-07-12 17:10 UTC, hunterloftis approved these changes

2023-07-12 17:49 UTC, merged