feat(menu): added support for menu item description
adobe/spectrum-web-components pull request #3559
Opened 2023-08-21 06:56 UTC by TarunAdobe

Added support for menu-item description

## Description

Added a description slot in the menu-item that can be used to show description of the corresponding menu-item. With this update the menu-item would match to the existing core tokens work.

## Related issue(s)

-[3258](https://github.com/adobe/spectrum-web-components/issues/3258)

## Motivation and context

Menu items should support a description to match what currently exists in core tokens work.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)
<img width="605" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/137032355/a9d17e31-3e51-4be4-9946-69d52281df70">
<img width="1073" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/137032355/2d721f65-53c5-4f0f-b590-061d55d8734d">

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2023-08-21 07:13 UTC, Rajdeepc submitted a review, later dismissed

2023-08-21 17:29 UTC, najikahalsema requested changes
Looks good, but I think we need to add at least a baseline test to account for these new changes. 

- I'd like to see a baseline test that renders the menu item as expected; similar to other tests for menu elements.

I would also recommend adding some menu items with descriptions to the different stories like disabled, selection states, etc, to test the visual changes.

2023-08-22 17:32 UTC, najikahalsema requested changes
Thanks for addressing the changes! One little thing and we're good to go.

2023-08-22 17:32 UTC, najikahalsema commented on packages/menu/stories/menu.stories.ts
> +export const menuItemHasDescription = (): TemplateResult => {
```suggestion
export const menuItemWithDescription = (): TemplateResult => {
```

2023-08-23 06:01 UTC, Rajdeepc approved these changes
LGTM!!

2023-08-23 06:34 UTC, blunteshwar submitted a review, later dismissed

2023-08-28 12:47 UTC, Westbrook commented on packages/menu/src/MenuItem.ts
> +            <span class="description">
The way this is leveraged in concert with the CSS makes the Menu Items each an extra 1px tall. Seems to come from it having a `1px` top margin...

2023-08-28 22:49 UTC, Westbrook commented on packages/menu/src/MenuItem.ts
> +            <span class="description">
Looks like _maybe_ this could leverage `[name=description]::slotted(*)` rather than the `.description` element.

2023-08-29 12:02 UTC, Westbrook commented on packages/menu/test/menu-item.test.ts
> +        expect(descriptionSlot).to.not.be.null;
Testing wise, this tests that the code you wrote above went unchanged when rendered to the page. In the case that you are testing a renderer, great, in the case that you're testing a custom element, maybe not the most productive. The assertion to guarantee the contract here is more likely:
```suggestion
        expect(descriptionElement.assignedSlot).to.not.be.null;
```
I might change the title of the test to `'assigns content to the "description" slot'`, and change the name of the variable used to `descriptionElement` as the "description slot" is the `<slot name="description">` element within the shadow DOM of the Menu Item.

2023-08-29 12:02 UTC, Westbrook reviewed
Those selectors and the visual output look much better. One other tweak to the test and I'm good to go, but I'll confirm with @najikahalsema once she's online before we merge.

2023-08-29 17:56 UTC, najikahalsema requested changes
Please review the change requested and it should be good to go.

2023-08-29 17:56 UTC, najikahalsema commented on packages/menu/test/menu-item.test.ts
> +        expect(descriptionElement).to.not.be.null;
Agree with Westbrook that this should be updated to `descriptionElement.assignedSlot` as he noted.

2023-08-30 11:45 UTC, Westbrook approved these changes
LGTM! Thanks for working through the testing context here, lots of nuance there but having unit test support for this going forward is gonna be super helpful.

2023-08-30 11:45 UTC, Westbrook commented
Oof, there's a conflict that I missed. Clean that up and we're good to go here!

2023-08-31 11:28 UTC, Westbrook approved these changes
Noice! Let's ship it. Great new feature for this element. 🥳

2023-08-31 11:42 UTC, merged