chore(coachmark): added separator property
adobe/spectrum-web-components pull request #4215
Opened 2024-03-26 10:54 UTC by Rajdeepc

## Description

This PR adds the ability for users to customize the separator between the current step and the total steps in the YourComponent component. By default, the separator is 'of', but users can now specify a custom separator using the separator attribute.

### Changes Made
Added a new separator property to the YourComponent component to allow customization of the separator.
Updated the component's template to use the separator property for the separator between the current step and the total steps.

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Use the separator attribute to specify a custom separator, e.g., <your-component separator="-"></your- component>.
    3. Verify that the component renders with the custom separator between the current step and the total steps.
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)
![Screenshot 2024-03-26 at 4 23 54 PM](https://github.com/adobe/spectrum-web-components/assets/8790510/379ad2ca-60e9-43c9-b7a5-56646819e606)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-03-26 12:27 UTC, Westbrook commented
Can you sync with the internationalization team to confirm that this works across the actual usage of our target languages? Naively, I've seeing `1 of 4` translate to `4 件中 1 件` in Japanese which I'm not sure how this API covers. Even a greatly simplified `４分の１` which might benefit from this change requires a content order change that I'm not sure a good path to managing here.

2024-03-26 17:28 UTC, Rajdeepc commented
> Can you sync with the internationalization team to confirm that this works across the actual usage of our target languages? Naively, I've seeing `1 of 4` translate to `4 件中 1 件` in Japanese which I'm not sure how this API covers. Even a greatly simplified `４分の１` which might benefit from this change requires a content order change that I'm not sure a good path to managing here.

I had a talk with the Internationalisation team and they said we cannot do string concatenation. We have to provide them a slot so that the entire string should be populated by the user.

2024-03-27 12:04 UTC, Westbrook reviewed
I'd like one of the stories to deliver a previously unachievable page count text to ensure that we can continue to achieve it over time.

2024-03-27 12:04 UTC, Westbrook commented on packages/coachmark/src/Coachmark.ts
> +                    <slot name="step-count"></slot>
```suggestion
                    <slot name="step-count">${this.currentStep} of ${this.totalSteps}</slot>
```
I think we should default to the English delivery here in order to reduce chances of happy path issues.

2024-03-27 12:04 UTC, Westbrook commented on packages/coachmark/README.md
> +    separator="out of"
We're removed this property, correct?

2024-03-29 03:56 UTC, Rajdeepc commented
@Westbrook Let me know if we are good to close this or do you see any additional work that needs to be done here?

2024-03-29 13:02 UTC, Westbrook commented
> I'd like one of the stories to deliver a previously unachievable page count text to ensure that we can continue to achieve it over time.

Can we see this in a story that surfaces to VRT to ensure we're covered over time? Something like `４分の１` or other.

2024-04-01 15:01 UTC, Westbrook approved these changes
LGTM! :shipit: 🎆

2024-04-01 15:04 UTC, Westbrook requested changes
Sorry, I missed one thing that I can't place inline...

Can you add:
```
 * @slot step-count - Override the default pagination delivery with your own internationalized content
```
At or around line 40 so that it gets into the docs site.

2024-04-02 13:15 UTC, Westbrook approved these changes
:shipit: but, like, for real this time 😉

2024-04-02 13:15 UTC, merged