feat(picker): allow customisation of popover height
adobe/spectrum-web-components pull request #4566
Opened 2024-06-17 13:59 UTC by Rocss

## Description

Adds CSS custom property to adjust the popover height when needed.

## Related issue(s)

- https://github.com/adobe/spectrum-web-components/issues/4564

## Motivation and context

For scenarios where there are a lot of options in the dropdown and the dropdown spawns the entire screen.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-06-18 05:35 UTC, Rajdeepc submitted a review, later dismissed
This is fine for now! But I will talk to css to get this in from the @spectrum-css/popover

2024-06-18 11:01 UTC, Rajdeepc requested changes
Technically this looks ok! But I would love to have some discussions from the design as well with the @spectrum-css/popover before we add this additional feature to the popover. Can you start a thread on this please on the qotd channel?

2025-02-26 21:56 UTC, caseyisonit commented
@Rajdeepc @Rocss what was the outcome of the qotd slack thread? Is this PR still valid or should it be closed?

2025-02-27 09:53 UTC, rubencarvalho commented
Closing - design doesn't want the block size of the popover to be customizable.

2025-02-27 09:53 UTC, closed without merging