chore: expand docs about the overlay directive
adobe/spectrum-web-components pull request #4588
Opened 2024-07-04 07:11 UTC by TarunAdobe

## Description

This PR expands the documentation for the overlay trigger directive and the tooltip directive in lines of making this public for consumers.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-07-05 09:32 UTC, TarunAdobe commented
Wrote an article as to support the annoucement of this feature -> https://paper.dropbox.com/doc/The-faster-way-to-use-overlay-s--CSX8sRV3gUM3EkuoHK~qHaPoAQ-pWTzVGccRnQos1DONYRSE

2024-07-08 09:04 UTC, Rajdeepc requested changes

2024-07-08 09:04 UTC, Rajdeepc commented on packages/overlay/trigger-directive.md
>  Pass a `TemplateResult` into the `trigger()` directive, as follows in order to have it rendered to the DOM when the associated Overlay is about to open and the removed after the Overlay has closed.
Can you also help the consumers understand the specific use cases where they will try to think through this implementation?

2024-07-09 06:35 UTC, Rajdeepc approved these changes
LGTM!

2024-07-09 06:37 UTC, blunteshwar approved these changes

2024-07-09 06:38 UTC, merged