fix(reactive-controllers): updated matchmedia mobile detection conditions
adobe/spectrum-web-components pull request #4656
Opened 2024-08-07 09:59 UTC by TarunAdobe

## Description

MatchMediaController would now `window.screen.availHeight` and `window.screen.availWidth` in conjunction with`window.matchMedia` to detect a mobile device accurately. 

## Related issue(s)

#4647 

## Motivation and context

Inconsistency in Picker, Action-Menu opening as `popover` vs `tray` in iPad devices after changing orientation.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-08-08 11:35 UTC, rubencarvalho requested changes
Let us dive deeper into avoiding attaching an event listener to each component, i.e., let's explore the singleton approach.

2024-08-19 21:15 UTC, lazd reviewed
Agreed that this needs to be done as a singleton, if this controller is on every element, we don't want thousands of listeners.

2024-08-19 21:15 UTC, lazd commented on tools/reactive-controllers/src/MatchMedia.ts
> +            (window.screen.availWidth < 768 || window.screen.availHeight < 768);
Very interesting! Wondering how this works around issues with `mediaMatches`?

2024-08-20 09:38 UTC, rubencarvalho commented on tools/reactive-controllers/src/MatchMedia.ts
> +    protected screenSize: 'small' | 'large' = 'small';
Could we create some `enum`s for `screenSize` and `orientation`?

2024-08-20 09:38 UTC, rubencarvalho commented on tools/reactive-controllers/src/MatchMedia.ts
> +                this.onChange.bind(this)
nit: I believe our code style typically uses arrow functions for binding `this`

2024-08-20 09:38 UTC, rubencarvalho commented on tools/reactive-controllers/src/MatchMedia.ts
> +    protected mediaQueryList!: MediaQueryList;
nit: could we have a more descriptive name for this one? The name `mediaQueryList` confuses me a bit when reading through the code. Maybe something like `customMediaQueryList` would be clearer that this is used when a custom media query is passed?

2024-08-20 09:38 UTC, rubencarvalho commented on tools/reactive-controllers/src/MatchMedia.ts
>      key = Symbol('match-media-key');
What is this `key` used for?

2024-08-20 09:38 UTC, rubencarvalho commented on tools/reactive-controllers/src/MatchMedia.ts
> +        const screenSize = this._determineScreenSize();
Could we encapsulate this "check if is mobile" logic into a dedicated method?

```ts
private _checkIsMobile(): boolean {
  const screenSize = this._determineScreenSize();
  const orientation = this._determineScreenOrientation();
  const isMobileScreen = this.isMobileScreenQuery.matches;

  // if the screen size is small or the orientation is landscape and the device is mobile
  return isMobileScreen && (screenSize === screenSize.small || orientation === orientation.landscape);
}
```

and then

```ts
this.matches = _checkIsMobile()
```

2024-08-20 12:14 UTC, Rajdeepc approved these changes
This is good to unblock for now! Let's think through a context level approach in achieving this in a follow up PR!

2024-08-20 13:12 UTC, merged