chore(reactive-controllers): updates lit dependency ti include
adobe/spectrum-web-components pull request #4744
Opened 2024-09-13 18:19 UTC by jnjosh

## Description

When we updated to support Lit 2 or Lit 3 we left Reactive Controllers behind, only supporting 3. This has created downstream issues in consumers that don't support Lit 3.

## How has this been tested?

- [ ] Need some help in how to best test this.

## Checklist

-   [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [X] My code follows the code style of this project.
-   [X] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [X] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [-] I have added tests to cover my changes.
-   [-] All new and existing tests passed.
-   [X ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-09-13 22:34 UTC, rubencarvalho approved these changes
I took a note to add downstream dummy consumers with different constraints to dry-run our upcoming releases. This would then be caught.
Thank you for fixing!

2024-09-14 11:01 UTC, TarunAdobe approved these changes
I love such PRs!!

2024-09-15 13:35 UTC, Rajdeepc requested changes
Awesome! But sadly this will not work. `reactive-controllers` will need to be pointed to `^3.1.3` since `@spectrum-web-components/reactive-controllers 0.42.2 depends on lit ^3.1.3` which means `^2.5.0 || ^3.1.3` will not be not true in this case.

2024-09-16 15:49 UTC, graynorton commented
> `reactive-controllers` lit dependency needs to be pointed to `^3.1.3`

@Rajdeepc, can you provide any detail on why the `@spectrum-web-components/reactive-controllers` package won't work with Lit `2.5.0`?

2024-09-19 11:24 UTC, Rajdeepc commented
> > `reactive-controllers` lit dependency needs to be pointed to `^3.1.3`
> 
> @Rajdeepc, can you provide any detail on why the `@spectrum-web-components/reactive-controllers` package won't work with Lit `2.5.0`?

My initial findings is that with `lit: 2.5.0`, storybook `7.x` is not supported under @storybook/types. Still digging into it!

2024-09-19 22:02 UTC, graynorton commented
> My initial findings is that with `lit: 2.5.0`, storybook `7.x` is not supported under @storybook/types. Component preview breaks under S7.

@Rajdeepc Let's try to sync up next week, maybe in the internal discussions meeting on Tuesday. I tried a bunch of things and couldn't identify any failures as a result of making this change, so would be good to compare notes. Thanks!

2025-02-26 22:10 UTC, caseyisonit commented
@graynorton @Rajdeepc what was the outcome of the convo mentioned above? Do we still support Lit2? If so we should get this in

2025-02-27 09:57 UTC, rubencarvalho commented
This got fixed by https://github.com/adobe/spectrum-web-components/pull/5105. Closing.

2025-02-27 09:57 UTC, closed without merging