chore: testing s2 icons delivery
adobe/spectrum-web-components pull request #4747
Opened 2024-09-16 07:37 UTC by TarunAdobe

## Description

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-09-24 09:14 UTC, Rajdeepc requested changes

2024-09-26 07:30 UTC, TarunAdobe commented on package.json
> -                "node_modules/@adobe/spectrum-css-workflow-icons/dist/18/**.svg"
yes because we're now setting these variables from the build-script itself.

2024-09-26 07:31 UTC, TarunAdobe commented on packages/icons-workflow/package.json
>          "@adobe/spectrum-css-workflow-icons": "^1.5.4",
yes done!

2024-09-26 07:31 UTC, TarunAdobe commented on packages/icon/src/IconBase.ts
> +type SystemVariant = 'spectrum' | 'spectrum-two' | 'express' | '';
Good catch. Thnx!

2024-10-07 11:56 UTC, merged

2025-01-06 18:35 UTC, lazd commented on packages/icon/src/spectrum-icon.css
> +    overflow: hidden;
Hmm, this change introduced clipped icons in Safari. Can you justify why this code was added?