chore: add 'system' context to `sp-theme`
adobe/spectrum-web-components pull request #4755
Opened 2024-09-16 18:54 UTC by rubencarvalho

## Description

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-09-25 08:47 UTC, Rajdeepc commented on packages/icon/src/Icon.ts
>          super.connectedCallback();
I feel a ghost call also takes up memory!

2024-09-25 10:41 UTC, Rajdeepc requested changes

2024-09-25 10:41 UTC, Rajdeepc commented on packages/icon/src/Icon.ts
> +type SystemVariant = 'spectrum' | 'spetrum-two' | 'express' | '';
```suggestion
import type {
    SystemVariant
} from '@spectrum-web-components/theme';
```

2024-09-25 10:41 UTC, Rajdeepc commented on tools/theme/src/Theme.ts
> +    private _handleSystemContext(
Documentation block?

2024-10-07 13:48 UTC, Rajdeepc reviewed
Neat! Also please add this controller in this [README.md] (https://github.com/adobe/spectrum-web-components/blob/testing-css-bridge-for-s2/tools/reactive-controllers/README.md#L0-L1) and we can land this!

2024-10-08 07:12 UTC, Rajdeepc approved these changes

2024-10-08 13:45 UTC, merged

2024-11-19 22:34 UTC, charlessuh commented
@rubencarvalho: I believe `@spectrum-web-components/reactive-controllers` is [missing](https://github.com/adobe/spectrum-web-components/blob/8d2790376b9cc09b543dfde3dcb778709b4394f9/packages/icon/package.json#L73) as a dependency in the `package.json` of the icon package. Can you add it?

2024-11-20 05:16 UTC, TarunAdobe commented
@charlessuh this `reactive-controller` is not meant to be used outside of our library and we haven't documented it either. Could you please explain better how this missing dependency is affecting your use-case?