[DO NOT MERGE]: accessibility docs for SWC05
adobe/spectrum-web-components pull request #4757
Opened 2024-09-16 20:54 UTC by nikkimk

## Description

Improving the accessibility documentation of components.

## Related issue(s)

- #4210 
-

## Motivation and context

Documentation should provide more information and examples that demonstrate how to use the components accessibly.

## How has this been tested?

-   [ ] `<sp-icon>` - Review [picker docs](https://nikkimk-a11y-docs--spectrum-web-components.netlify.app/components/icon/)
    
-   [ ] `<sp-icons>` - Review [menu docs](https://nikkimk-a11y-docs--spectrum-web-components.netlify.app/components/icons/)
    
-   [ ] `<sp-iconset>` -Review [help text docs](https://nikkimk-a11y-docs--spectrum-web-components.netlify.app/components/iconset/)

 - [ ] `<sp-icons-ui>` - Review [button docs](https://nikkimk-a11y-docs--spectrum-web-components.netlify.app/components/icons-ui/)

 - [ ] `<sp-icons-workflow>` - Review [button group docs](https://nikkimk-a11y-docs--spectrum-web-components.netlify.app/components/icons-workflow)

 
-  [ ] Are the examples accessible?
-  [ ] Do the docs examples and text provide information on how to use the component accessibly?
-  [ ] If the component is to be used in the context of another component, do the examples include how that component is used accessibly in that context?
- [ ] Are the docs headings logical and consistent across these components?

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes. **_N/A_**
-   [ ] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-09-17 06:09 UTC, Rajdeepc requested changes
Thanks for doing this! This will definitely help improve the documentation guidelines for our library. Though I see issues with the css on the tabs. It would be great if you could take a look at those before we do an official review!

2024-10-02 14:04 UTC, nikkimk commented
> Though I see issues with the css on the tabs. It would be great if you could take a look at those before we do an official review!

@Rajdeepc Can you be more specific about the issues with tabs please? Do you mean the Overview /API / Changelog tabs, the Tabs component documentation, or something else?  Thanks!

2024-10-08 04:47 UTC, Rajdeepc commented
> * Documentation Site
Please review the changes. The Docs site is distorted. Check H1 and H2!

<img width="1243" alt="Screenshot 2024-10-08 at 10 16 39 AM" src="https://github.com/user-attachments/assets/67c6e44c-e88a-403f-9882-eeae039b8e9e">

2024-10-11 14:35 UTC, nikkimk commented
@Rajdeepc visual changes and heading hierarchy changes were intentional for accessibility. The heading markup reflects the content hierarchy now. Heading font sizes for all headings have increase so that subheadings are also accessible.

2024-10-17 17:49 UTC, najikahalsema requested changes
Looking good! Just a few things.

2024-10-17 17:49 UTC, najikahalsema commented on packages/icons/README.md
>  The `<sp-icons-medium>` and `<sp-icons-large>` elements that are included in this package supply your application with the Spectrum CSS Icons at both the medium and large sizes for use via the `<sp-i
```suggestion
The `<sp-icons-medium>` and `<sp-icons-large>` elements included in this package supply your application with the Spectrum CSS medium and large icons for use in the `<sp-icon>` element. Include at least one of these elements in a project that makes use of icons in these sets. You can also include these sets in the scope of any element that leverages them, as they will be deduplicated to ensure all of your components can deliver the icons included therein.
```

2024-10-18 16:22 UTC, nikkimk commented on packages/action-menu/README.md
>  An `<sp-action-menu>` is an action button that triggers an overlay with `<sp-menu-items>` for activation. Use an `<sp-menu>` element to outline the items that will be made available to the user when
Trigger happy is fine by me :)

2024-10-18 21:59 UTC, nikkimk commented on packages/help-text/README.md
> +#### Negative
I renamed Variants to Options to better align with design's documentation

2024-10-22 16:02 UTC, nikkimk commented
@Rajdeepc got the following design recommendations and implemented them:

- h1: heading XXL, serif, heavy
- h2: heading L, sans-serif
- h3: heading M, sans-serif
- h4: heading S, sans-serif
- h5: detail L

Please take another look, keeping in mind that the scope of review should be limited to the heading changes and the documentation listed above. 

**Note:** _This PR (originally for sprint SWC05) will get merged into the #4756 where all the docs will be getting a final review._

2024-10-22 19:52 UTC, najikahalsema approved these changes
LGTM!! Thank you!!!

2024-10-24 06:04 UTC, Rajdeepc approved these changes

2024-10-24 13:17 UTC, closed without merging