fix(menu): allow keyboard events to propagate from opened menu
adobe/spectrum-web-components pull request #4793
Opened 2024-10-01 09:06 UTC by TarunAdobe

## Description

An opened sp-menu should allow application keyboard shortcuts.

## Related issue(s)

- #4786

## Motivation and context

An opened sp-menu doesn't allow application keyboard shortcuts, stopping the propagation of almost all keydown events.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-10-01 10:21 UTC, blunteshwar approved these changes
LGTM! 🔥

2024-10-01 10:55 UTC, Rajdeepc approved these changes

2024-10-01 11:50 UTC, rubencarvalho requested changes
Let us further discuss if this is the most adequate approach to solving this issue. We are diverging from the native `select` element behaviour which, when opened, captures focus and directs keyboard events specifically towards interacting with its options (even though we currently have not implemented the "interacting with its options" part).

Can we check if consumers can solve this on their side by adding an event listener in the capture phase instead of relying solely on the bubbling phase?

2024-10-01 14:37 UTC, lazd commented
> Let us further discuss if this is the most adequate approach to solving this issue. We are diverging from the native `select` element behaviour which, when opened, captures focus and directs keyboard events specifically towards interacting with its options (even though we currently have not implemented the "interacting with its options" part).

Good point, I didn't realize `<select>` eats all keyboard events when opened, even listeners added with `capture: true`! However, I can still use keyboard shortcuts such as `Command W` and `Command +` when focused on and interacting with a `<select>`.

> Can we check if consumers can solve this on their side by adding an event listener in the capture phase instead of relying solely on the bubbling phase?

This would work and was actually my first inclination. I suppose we should speak with accessibility and ask what they think the best behavior is here.

2024-11-07 20:58 UTC, rubencarvalho commented
Hello @lazd, can you confirm if you could solve this on your side?

2024-11-11 18:58 UTC, lazd commented
Hey @rubencarvalho, unfortunately, we're unable to use a capture listener on our side to work around this bug.

This behavior in SWC was actually [introduced 4 months ago in a feature PR that was adding support for action menus in action bars](https://github.com/adobe/spectrum-web-components/pull/3780/files#r1656403552), apparently to prevent a potential bug:

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/6472532e-b2df-464a-b92f-683fd96a801b">

It was never intentionally added to model behavior after `<select>`, and this is clearly an unintended side effect of that change.

I suggest we merge this PR after testing that the original but this change was meant to address is no longer happening. Thank you!

2025-02-26 22:19 UTC, caseyisonit commented
@rubencarvalho @nikkimk @TarunAdobe  can we confirm if the menu omnibus accessibility work addressed this issue? or what conversations do we need to have to update the status on this PR?

2025-02-27 10:01 UTC, rubencarvalho commented
For this particular case, we agreed that consumers should handle it on the application level (resolved in Slack thread).
There is a similar issue opened here about other components: https://github.com/adobe/spectrum-web-components/issues/5099

2025-02-27 10:01 UTC, closed without merging