chore: added eslint plugin import check on missing dependencies
adobe/spectrum-web-components pull request #4928
Opened 2024-11-11 08:42 UTC by Rajdeepc

## Description

Added `eslint-plugin-import` plugin to check for extraneous dependencies. 

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-11-11 09:01 UTC, blunteshwar reviewed
Certain tests are failing. Once we rectify them I think we are good to go!

2024-11-11 10:58 UTC, rubencarvalho requested changes
We need to check multiple things:
1. It would be best if we applied the same rule across the entire project. Currently, this only applies to `./tools/*`, but we also have a root-level `eslintrc.json` file.
2. If we apply it globally, I’d say `projects/documentation` is safe to ignore.
3. This change will likely trigger numerous linting errors, which should be addressed within the scope of this PR.
4. Can we check if switching to JS-based ESLint configs (instead of JSON) might better support the required changes? This would allow us to add more complex path/package-parsing logic if needed.

2025-02-26 23:35 UTC, caseyisonit commented
@Rajdeepc @rubencarvalho is this still an active initiative or should we start a fresh PR when a Jira ticket is on our board?

2025-06-12 10:02 UTC, Rajdeepc commented
closing as it is resolved now

2025-06-12 10:02 UTC, closed without merging