fix(overlay): returning only the first element for slot assignedElements
adobe/spectrum-web-components pull request #4930
Opened 2024-11-11 18:20 UTC by zolar

Only return first element form `assignedElements` instead of an array of elements.

## Description

This follows a pattern used by Horizon to only use return the first element for the shot handler of the OverlayTrigger. Their appears to be an issue returning and array or elements that lead to a recursive loop that never stops in our component. Since only the first element is used this change should be benign.

## Related issue(s)
  

[[Bug]: OverlayTrigger can get stuck in a render loop causing page to crash](https://github.com/adobe/spectrum-web-components/issues/4689)

## Motivation and context

Resolves an issue related to endless render loop.

## How has this been tested?

-   [x] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

#### N/A

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2024-11-26 08:13 UTC, Rajdeepc commented
We would like to see you use case here considering this is very specific. Can you add a video or a repro to show how does this solve your issue?

2024-11-26 19:01 UTC, zolar commented
> We would like to see you use case here considering this is very specific. Can you add a video or a repro to show how does this solve your issue?

@Rajdeepc Yes, I can add a video or we can do another debug session so I can walk threw it with you or you team?

2024-11-27 07:38 UTC, zolar commented
@Rajdeepc This is a video of the component not rendering. The component container stays blank and you can see the console output going forever. It will eventually crash the browser. 

https://github.com/user-attachments/assets/dacc1d68-6b89-4f7b-b62e-147ab35cfb1c

2024-11-27 14:43 UTC, Rajdeepc commented
> @Rajdeepc This is a video of the component not rendering. The component container stays blank and you can see the console output going forever. It will eventually crash the browser.
> 
>  Sequence.low.02.mp4

This seems to be a condition where the entire component is re-rendering multiple times due to state or property changes. Can you do a repro of your use case by any means?

2024-11-27 17:46 UTC, zolar commented
> > @Rajdeepc This is a video of the component not rendering. The component container stays blank and you can see the console output going forever. It will eventually crash the browser.
> > Sequence.low.02.mp4
> 
> This seems to be a condition where the entire component is re-rendering multiple times due to state or property changes. Can you do a repro of your use case by any means?

@Rajdeepc 
This issue is only repoing in Express app. We have an example / development application in which we do not see this issue. I think that the issue has to do with Express being so resource intensive. I think this is a race condition in which the Dialog is not completely finished rendering when the `slothandler` attaches to the slot content, which forces it to `rerender`. I think that using he `nodes.find` delays in just enough that the Dialog completes rendering. The issue can also be fixed using the current `slot.assignedElements` and a zero wait promise `new Promise(resolve => setTimeout(resolve, 0));`. 

Express does use Service Workers but its still very resource heavy and I think its effecting the rendering of our component. We also use a lot of OverlayTriggers that might effect render changes also.

2024-12-10 18:43 UTC, zolar commented
> > @Rajdeepc This is a video of the component not rendering. The component container stays blank and you can see the console output going forever. It will eventually crash the browser.
> > Sequence.low.02.mp4
> 
> This seems to be a condition where the entire component is re-rendering multiple times due to state or property changes. Can you do a repro of your use case by any means?

@Rajdeepc This only happens in Express, it does not repo in our development at or any other environment that I know of. There maybe a late state change that is happening but its not from a map or any other iterator that I could find. I think its just a normal state change or its being delayed by the slag in the process.

2025-01-02 08:09 UTC, Rajdeepc requested changes
Can you please make sure that the PR is clean from any css related changes on radio and search!

2025-01-02 08:15 UTC, Rajdeepc commented
@zolar Also please check the tests in `overlay-trigger-longpress.test.ts` line 222 which needs to flatten to
```js
            await waitUntil(() => {
                const localName = (
                    this.el as unknown as { targetContent: HTMLElement }
                ).targetContent?.localName;
```

2025-01-14 23:34 UTC, zolar commented
Closing this PR since this does not fix the root cause.

2025-01-14 23:34 UTC, closed without merging