chore: make scroll consistent in long popover vrts
adobe/spectrum-web-components pull request #4957
Opened 2024-11-26 10:07 UTC by TarunAdobe

## Description

## Related issue(s)

-

## Motivation and context

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Screenshots (if appropriate)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

2025-02-26 23:30 UTC, caseyisonit commented
@TarunAdobe is this still a help test fix to add in?

2025-02-27 06:59 UTC, TarunAdobe commented
> @TarunAdobe is this still a help test fix to add in?

Could be. I still need to verify if this resolves the VRT flakiness or not. Will take a look today

2025-02-27 10:06 UTC, rubencarvalho commented
There is also a picker with icons VRT that is sometimes flaky, please take a look at it in scope of this ticket. Thanks!

2025-03-04 14:21 UTC, Rajdeepc requested changes

2025-03-04 14:32 UTC, TarunAdobe commented on packages/overlay/stories/index.ts
> +        await nextFrame();
noooooooo....
// Focus happens _after_ `sp-opened` by at least two frames.

2025-03-04 14:39 UTC, TarunAdobe commented on packages/overlay/stories/index.ts
> +        this.ready(true);
I fail to see when this will happen?

2025-03-04 14:46 UTC, caseyisonit commented on packages/overlay/stories/index.ts
> +        await nextFrame();
Use elementUpdated() instead, I’ll slack you the link I used last night

2025-03-04 14:50 UTC, TarunAdobe commented on packages/overlay/stories/index.ts
> +        await nextFrame();
yessssss plz

2025-03-04 14:51 UTC, TarunAdobe commented on packages/overlay/stories/index.ts
> +        await nextFrame();
oh wait i dont the elementUpdated works here. I tried. element will be updated bt the browser will take a few frames to set focus on the selected item and that we cannot control so we just wait some extra frames to avoid the flakiness!

2025-03-05 07:33 UTC, TarunAdobe commented on packages/overlay/stories/index.ts
> +                const img = new Image();
Done!!

2025-03-05 11:44 UTC, Rajdeepc approved these changes

2025-03-05 15:04 UTC, rubencarvalho approved these changes

2025-03-05 15:05 UTC, merged